spring:
  application:
    name: SuperMarket

  datasource:
    url: jdbc:mysql://localhost:3306/SuperMarket_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Bogota
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

server:
  port: 8080
  error:
    include-message: always